services:
  db:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: clinica
      POSTGRES_DB: clinica
    ports:
      - 5437:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: